joseph/sql_ar/config/routes.rb
Rails.application.routes.draw do
  
  root 'flowers#index'
  
  resources :flowers
  resources :weathers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

joseph/sql_ar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

joseph/sql_ar/app/models/flower.rb
class Flower < ApplicationRecord
end

joseph/sql_ar/app/models/weather.rb
class Weather < ApplicationRecord
end

joseph/sql_ar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

joseph/sql_ar/app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

  # GET /flowers
  # GET /flowers.json
  def index
    @flowers = Flower.all
  end

  # GET /flowers/1
  # GET /flowers/1.json
  def show
  end

  # GET /flowers/new
  def new
    @flower = Flower.new
  end

  # GET /flowers/1/edit
  def edit
  end

  # POST /flowers
  # POST /flowers.json
  def create
    @flower = Flower.new(flower_params)

    respond_to do |format|
      if @flower.save
        format.html { redirect_to @flower, notice: 'Flower was successfully created.' }
        format.json { render :show, status: :created, location: @flower }
      else
        format.html { render :new }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flowers/1
  # PATCH/PUT /flowers/1.json
  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to @flower, notice: 'Flower was successfully updated.' }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.json
  def destroy
    @flower.destroy
    respond_to do |format|
      format.html { redirect_to flowers_url, notice: 'Flower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flower_params
      params.require(:flower).permit(:name, :smell, :pretty, :height)
    end
end

joseph/sql_ar/app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url, notice: 'Weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:name, :intensity, :scary)
    end
end

joseph/sql_ar/app/helpers/application_helper.rb
module ApplicationHelper
end

joseph/sql_ar/app/helpers/flowers_helper.rb
module FlowersHelper
end

joseph/sql_ar/app/helpers/weathers_helper.rb
module WeathersHelper
end

joseph/sql_ar/app/views/flowers/_form.html.erb
<%= form_with(model: flower, local: true) do |form| %>
  <% if flower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flower.errors.count, "error") %> prohibited this flower from being saved:</h2>

      <ul>
      <% flower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :flower_name %>
  </div>

  <div class="field">
    <%= form.label :smell %>
    <%= form.text_field :smell, id: :flower_smell %>
  </div>

  <div class="field">
    <%= form.label :pretty %>
    <%= form.check_box :pretty, id: :flower_pretty %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, id: :flower_height %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

joseph/sql_ar/app/views/flowers/edit.html.erb
<h1>Editing Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Show', @flower %> |
<%= link_to 'Back', flowers_path %>

joseph/sql_ar/app/views/flowers/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Flowers</h1>
    <p>Flowers are so great!</p>
    <p><%= link_to 'Create a Flower', new_flower_path, :class => 'btn btn-primary btn-lg' %>
  </div>
</div>
<div class="container">
  <div class="row">
  <p id="notice"><%= notice %></p>
  </div>

  <div class="row">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col" class="col-3">Name</th>
        <th scope="col" class="col-3">Smell</th>
        <th scope="col" class="col-2">Pretty</th>
        <th scope="col" class="col-2">Height</th>
        <th scope="col" class="col-2"></th>
      </tr>
    </thead>

    <tbody>
      <% @flowers.each do |flower| %>
        <tr>
          <td scope="col"><%= flower.name %></td>
          <td scope="col"><%= flower.smell %></td>
          <td scope="col"><%= flower.pretty %></td>
          <td scope="col"><%= flower.height %></td>
          <td scope="col">
            <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to 'Show', flower, :class => 'btn btn-secondary' %>
            <%= link_to 'Edit', edit_flower_path(flower), :class => 'btn btn-secondary' %>
            <%= link_to 'Destroy', flower, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-secondary'%></td>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <br>

</div>

joseph/sql_ar/app/views/flowers/new.html.erb
<h1>New Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Back', flowers_path %>

joseph/sql_ar/app/views/flowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flower.name %>
</p>

<p>
  <strong>Smell:</strong>
  <%= @flower.smell %>
</p>

<p>
  <strong>Pretty:</strong>
  <%= @flower.pretty %>
</p>

<p>
  <strong>Height:</strong>
  <%= @flower.height %>
</p>

<%= link_to 'Edit', edit_flower_path(@flower) %> |
<%= link_to 'Back', flowers_path %>

joseph/sql_ar/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="#">App</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <%= link_to 'Flowers', flowers_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to 'Weather', weathers_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu" aria-labelledby="dropdown01">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>

joseph/sql_ar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SqlAr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

joseph/sql_ar/app/views/weathers/_form.html.erb
<%= form_with(model: weather, local: true) do |form| %>
  <% if weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :weather_name %>
  </div>

  <div class="field">
    <%= form.label :intensity %>
    <%= form.number_field :intensity, id: :weather_intensity %>
  </div>

  <div class="field">
    <%= form.label :scary %>
    <%= form.check_box :scary, id: :weather_scary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

joseph/sql_ar/app/views/weathers/edit.html.erb
<h1>Editing Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

joseph/sql_ar/app/views/weathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weathers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Intensity</th>
      <th>Scary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.name %></td>
        <td><%= weather.intensity %></td>
        <td><%= weather.scary %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

joseph/sql_ar/app/views/weathers/new.html.erb
<h1>New Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Back', weathers_path %>

joseph/sql_ar/app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weather.name %>
</p>

<p>
  <strong>Intensity:</strong>
  <%= @weather.intensity %>
</p>

<p>
  <strong>Scary:</strong>
  <%= @weather.scary %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>